version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - tibia-server
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - tibia-server
    links:
      - mariadb:db
    ports:
      - "8080:80"

volumes:
  mysql_data:
    driver: local
